-- View all customer data
SELECT * FROM customers;

-- View all order data
SELECT * FROM orders;

-- View all product data
SELECT * FROM products;

--------------------------------------------------

-- Business Question: Total revenue generated by each customer
SELECT c.customer_name,
       SUM(o.order_amount) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_revenue DESC;

--------------------------------------------------

-- Business Question: Number of orders placed by each customer
SELECT customer_id,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id;

--------------------------------------------------

-- Business Question: Customers with total revenue greater than 10,000
SELECT c.customer_name,
       SUM(o.order_amount) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING SUM(o.order_amount) > 10000;

--------------------------------------------------

-- Business Question: City-wise revenue analysis
SELECT c.city,
       SUM(o.order_amount) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY total_revenue DESC;
